version: '3.8'

services:
  heeyoung-server:
    container_name: heeyoung-server
    image: ${DOCKERHUB_USERNAME}/heeyoung-server:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: jdbc:mysql://database-1.c5waoswosxs9.ap-northeast-2.rds.amazonaws.com:3306/HEEYOUNG_DB?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dpwl0910!
      JWT_SECRET: 363a69e9501d9e1a1f8f475e3d21b8480048c29e583cd036dee05310404e2261
