services:
  heeyoung-server:
    container_name: heeyoung-server
    networks:
      - heeyoung-network
    image: ${DOCKERHUB_USERNAME}/heeyoung-server:latest
    ports:
      - "8001:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mysql://heeyoung-database:3306/heeyoungdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=0910
    depends_on:
      - heeyoung-database

  heeyoung-database:
    container_name: heeyoung-database
    networks:
      - heeyoung-network
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=0910
      - MYSQL_DATABASE=heeyoungdb
      - TZ=Asia/Seoul
    ports:
      - "3307:3306"

networks:
  heeyoung-network:
    driver: bridge