spring:
  datasource:
    url: jdbc:mysql://database-1.c5waoswosxs9.ap-northeast-2.rds.amazonaws.com:3306/HEEYOUNG_DB?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Dpwl0910!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000     # 30분
  refresh-token-expiration: 604800000  # 7일

logging:
  level:
    root: info
    org.springframework.web: warn
    org.springframework.security: warn
