name: heeyoung Workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Java 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle Build 수행
      - name: Grant execute permission for gradlew
        run: chmod +x ./contents/heeyoung/gradlew

      - name: Build with Gradle
        run: cd ./contents/heeyoung && ./gradlew clean build -x test

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/heeyoung-server:latest ./contents/heeyoung

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/heeyoung-server:latest

      - name: Deploy on EC2 (docker-compose)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/heeyoung
            docker-compose pull heeyoung-server
            docker-compose down
            docker-compose up -d
